[package]
name = "modular-bitfield-ordering"
version = "0.1.0"
edition = "2021"
authors = ["Pelepichenko Alexander <chabapok@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"


[dependencies]
modular-bitfield = "0"
